<?php 
/**
 * DO NOT CHANGE CURRENT PATH SETTINGS IF NOT FAMILIAR
 */
$this->plugin('basePath')->setBasePath("/");

// CSS Stylesheets
$favicon    = $this->basePath('assets/site/img/favicon.ico');
$style      = $this->basePath('assets/laracast/css/style.css');
$faIcon     = $this->basePath('assets/font-awesome/css/font-awesome.css');
$bootstrap  = $this->basePath('assets/bootstrap/css/bootstrap.min.css');
$bsTheme    = $this->basePath('assets/bootstrap/css/bootstrap-theme.min.css');

// JavaScripts
$jquery     = $this->basePath('assets/jquery/jquery.min.js');
$jqueryui   = $this->basePath('assets/jquery-ui/jquery-ui.min.js');
$bsJS       = $this->basePath('assets/bootstrap/js/bootstrap.min.js');
$popover    = $this->basePath('assets/bootstrap/js/popover.js');
$tooltip    = $this->basePath('assets/bootstrap/js/tooltip.js');
$tab        = $this->basePath('assets/bootstrap/js/tab.js');
$app        = $this->basePath('assets/site/js/app.min.js');
$dashboard  = $this->basePath('assets/site/js/pusher.js');
?>
<?php echo $this->doctype('HTML5') . "\n"; ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no');
        ?>
        <?php echo $this->headTitle()->setAutoEscape(false); ?>
        <?php 
            echo $this->headLink(['rel' => 'shortcut icon', 'href' => $favicon])
                    ->prependStylesheet($style)
                    ->prependStylesheet($faIcon)
                    ->prependStylesheet($bootstrap)
        ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">        
        <div class="wrapper">
            <header class="Header">
             <?php echo $this->partial('site/header'); ?>
            </header>
            <div class="container">
                <?php echo $this->content; ?>
            </div>
            <?php echo $this->partial('site/footer'); ?>            
        </div>
        <?php 
            echo $this->inlineScript() //prepend global script here
                    ->prependFile($bsJS)
                    ->prependFile($jqueryui)
                    ->prependFile($jquery);
        ?>
    </body>
</html>
