<section class="sidebar">      
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu">
    <li class="header">GENERAL OVERVIEW</li>
    <li class="active"><a href="<?php echo $this->url('home'); ?>">
        <i class="fa fa-dashboard"></i> <span>School Program</span></a>
    </li>
    <li class="active"><a href="#">
        <i class="fa fa-line-chart"></i> <span>Financial Report</span></a>
    </li>
    <li class="header">ADMISSION OFFICE</li>
    <li class="active"><a href="<?php echo $this->url('enrollment'); ?>">
        <i class="fa fa-dashboard"></i> <span>Enrollment</span></a>
    </li>
    <li class="active"><a href="<?php echo $this->url('student'); ?>">
        <i class="fa fa-group"></i> <span>Student</span></a>
    </li>
    <li class="active"><a href="<?php echo $this->url('faculty'); ?>">
        <i class="fa fa-user"></i> <span>Faculty</span></a>
    </li>
    <li class="active"><a href="<?php echo $this->url('prospectus'); ?>">
        <i class="fa fa-list-alt"></i> <span>Prospectus</span></a>
    </li>    
    <li class="treeview">
      <a href="#">
        <i class="fa fa-book"></i>
        <span>Documents</span>
        <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
        <li><a href="pages/layout/top-nav.html"><i class="fa fa-pencil-square-o"></i> Top Navigation</a></li>
        <li><a href="pages/layout/boxed.html"><i class="fa fa-pencil-square-o"></i> Boxed</a></li>
        <li><a href="pages/layout/fixed.html"><i class="fa fa-pencil-square-o"></i> Fixed</a></li>
        <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-pencil-square-o"></i> Collapsed Sidebar</a></li>
      </ul>
    </li>
    <li class="header">REPORTS</li>
    <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>                
  </ul>
</section>
    <!-- /.sidebar -->