<footer class="Footer">
    <div class="container">

        <div class="left">
            <h1 class="logo logo--light"><span class="l">l</span>aracasts</h1>

            <p class="description">
                Lots of your peers think Laracasts is one of the best things ever. So <a href="https://laracasts.com/join">buy Jeffrey lunch</a> once a month, see for yourself, and massively level up your skills in the process.
            </p>

            <ul class="social-links">
                <li class="social-link">
                    <a href="http://facebook.com/laracasts">
                        <img src="./Join_files/facebook.png">
                    </a>
                </li>

                <li class="social-link">
                    <a href="http://twitter.com/laracasts">
                        <img src="./Join_files/twitter.png">
                    </a>
                </li>

                <li class="social-link">
                    <a href="https://github.com/laracasts">
                        <img src="./Join_files/github.png">
                    </a>
                </li>
            </ul>
        </div>


        <div class="right">
            <div>
                <h5 class="heading">Learn</h5>

                <ul class="zeroed">
                    <li><a href="https://laracasts.com/lessons">Library</a></li>
                    <li><a href="https://laracasts.com/shop">Shop</a></li>
                    <li class=""><a href="https://laracasts.com/newsletters/2016/april">Newsletter</a></li>
                    <li><a href="https://laracasts.com/recommended-reading">Books</a></li>
                    <li><a href="https://laracasts.com/join">Sign Up</a></li>
                     <li><a href="https://laracasts.com/login">Log In</a></li>
                </ul>
            </div>

            <div>
                <h5 class="heading">Discuss</h5>

                <ul class="zeroed">
                    <li><a href="https://laracasts.com/discuss">Forum</a></li>
                    <li><a href="http://laracasts.audio/">Laracasts Podcast</a></li>
                    <li><a href="http://laravelpodcast.com/">Laravel Podcast</a></li>
                </ul>
            </div>


            <div>
                <h5 class="heading">Extras</h5>

                <ul class="zeroed">
                    <li><a href="https://laracasts.com/stats">Statistics</a></li>
                    <li><a href="https://laracasts.com/testimonials">Testimonials</a></li>
                    <li><a href="https://laracasts.com/faq">FAQ</a></li>
                    <li><a href="https://laracasts.com/contact">Get Support</a></li>
                    <li><a href="https://laracasts.com/feed">RSS</a></li>
                    <li><a href="https://forge.laravel.com/">Laravel Forge</a></li>
                    <li><a href="https://larajobs.com/?partner=36#">Larajobs</a></li>
                </ul>
            </div>

            <div>
                <h5 class="heading">Grown Up Stuff</h5>

                <ul class="zeroed">
                    <li><a href="https://laracasts.com/privacy">Privacy</a></li>
                    <li><a href="https://laracasts.com/terms">Terms</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<div class="Footer-Secondary">
    <div class="container">
        <div class="utility-left">
            <p class="copyright">
                © Laracasts 2016. All rights reserved.
                Yes, all of them.
            </p>

            <div class="hosting">
                Proudly hosted with <a href="https://forge.laravel.com/">Laravel Forge</a>
                and <a href="https://www.digitalocean.com/?refcode=d2070a2d5f35">DigitalOcean</a>.
            </div>
        </div>

        <form id="newsletter-form" class="utility-right" method="POST" action="https://laracasts.com/newsletters/subscribe"><div class="input-group"><input type="email" class="form-control" name="email" autocomplete="off" required="" placeholder="Sign up for the Monthly Newsletter"> <span class="input-group-btn"><button class="Button Button Button--Callout"><span>Subscribe</span><div class="la-ball-fall" style="display: none;"><div></div><div></div><div></div></div></button></span></div></form>

    </div>
</div>